version: "3.8"

networks: 
  job_application_network: 
    driver: bridge

services:
  
  rest-job-api:
    image: rest_job_api
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: cmd/rest/app.dockerfile
    env_file:
      - .env
    networks:
      job_application_network:
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:db"
  
  grpc-job-api:
    image: grpc_job_api
    ports:
      - "50053:50053"
    build:
      context: .
      dockerfile: cmd/grpc/app.dockerfile
    env_file:
      - .env
    networks:
      job_application_network:
    depends_on:
      db:
        condition: service_healthy
    links: 
      - "db:db"

  db:
    image: postgres:latest
    container_name: postgres_job_application
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Guboj=25
      POSTGRES_DB: job_application_db
      ports: 5433:5432
    networks:
      job_application_network:
  
  # migration:
  #   container_name: migration_job
  #   build:
  #     context: .
  #     target: "migration"
  #   env_file:
  #     - .env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     job_application_network:
  #   links:
  #     - "db:db"