// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// JobHandler is an autogenerated mock type for the JobHandler type
type JobHandler struct {
	mock.Mock
}

// CreateJob provides a mock function with given fields: c
func (_m *JobHandler) CreateJob(c *gin.Context) {
	_m.Called(c)
}

// GetAllJobs provides a mock function with given fields: c
func (_m *JobHandler) GetAllJobs(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewJobHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewJobHandler creates a new instance of JobHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJobHandler(t mockConstructorTestingTNewJobHandler) *JobHandler {
	mock := &JobHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
