// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "job-application/entity/models"

	query "job-application/query"
)

// JobUsecase is an autogenerated mock type for the JobUsecase type
type JobUsecase struct {
	mock.Mock
}

// CreateJob provides a mock function with given fields: ctx, job
func (_m *JobUsecase) CreateJob(ctx context.Context, job *models.Job) (*models.Job, error) {
	ret := _m.Called(ctx, job)

	var r0 *models.Job
	if rf, ok := ret.Get(0).(func(context.Context, *models.Job) *models.Job); ok {
		r0 = rf(ctx, job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Job) error); ok {
		r1 = rf(ctx, job)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllJobs provides a mock function with given fields: ctx, clauses
func (_m *JobUsecase) FindAllJobs(ctx context.Context, clauses []query.WhereClause) ([]models.Job, error) {
	ret := _m.Called(ctx, clauses)

	var r0 []models.Job
	if rf, ok := ret.Get(0).(func(context.Context, []query.WhereClause) []models.Job); ok {
		r0 = rf(ctx, clauses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Job)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []query.WhereClause) error); ok {
		r1 = rf(ctx, clauses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewJobUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewJobUsecase creates a new instance of JobUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJobUsecase(t mockConstructorTestingTNewJobUsecase) *JobUsecase {
	mock := &JobUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
