// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/job_application.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Birthdate            string   `protobuf:"bytes,2,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRequest) GetBirthdate() string {
	if m != nil {
		return m.Birthdate
	}
	return ""
}

func (m *UserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserLoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{1}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type JobRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quota                uint32   `protobuf:"varint,2,opt,name=quota,proto3" json:"quota,omitempty"`
	ExpiryDate           string   `protobuf:"bytes,3,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	JobPosterId          uint32   `protobuf:"varint,4,opt,name=job_poster_id,json=jobPosterId,proto3" json:"job_poster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobRequest) Reset()         { *m = JobRequest{} }
func (m *JobRequest) String() string { return proto.CompactTextString(m) }
func (*JobRequest) ProtoMessage()    {}
func (*JobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{2}
}

func (m *JobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRequest.Unmarshal(m, b)
}
func (m *JobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRequest.Marshal(b, m, deterministic)
}
func (m *JobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRequest.Merge(m, src)
}
func (m *JobRequest) XXX_Size() int {
	return xxx_messageInfo_JobRequest.Size(m)
}
func (m *JobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobRequest proto.InternalMessageInfo

func (m *JobRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobRequest) GetQuota() uint32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *JobRequest) GetExpiryDate() string {
	if m != nil {
		return m.ExpiryDate
	}
	return ""
}

func (m *JobRequest) GetJobPosterId() uint32 {
	if m != nil {
		return m.JobPosterId
	}
	return 0
}

type IdRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{3}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type WhereClause struct {
	Field                string   `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Condition            string   `protobuf:"bytes,3,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhereClause) Reset()         { *m = WhereClause{} }
func (m *WhereClause) String() string { return proto.CompactTextString(m) }
func (*WhereClause) ProtoMessage()    {}
func (*WhereClause) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{4}
}

func (m *WhereClause) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhereClause.Unmarshal(m, b)
}
func (m *WhereClause) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhereClause.Marshal(b, m, deterministic)
}
func (m *WhereClause) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhereClause.Merge(m, src)
}
func (m *WhereClause) XXX_Size() int {
	return xxx_messageInfo_WhereClause.Size(m)
}
func (m *WhereClause) XXX_DiscardUnknown() {
	xxx_messageInfo_WhereClause.DiscardUnknown(m)
}

var xxx_messageInfo_WhereClause proto.InternalMessageInfo

func (m *WhereClause) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *WhereClause) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *WhereClause) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type WhereClauses struct {
	Clauses              []*WhereClause `protobuf:"bytes,1,rep,name=clauses,proto3" json:"clauses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WhereClauses) Reset()         { *m = WhereClauses{} }
func (m *WhereClauses) String() string { return proto.CompactTextString(m) }
func (*WhereClauses) ProtoMessage()    {}
func (*WhereClauses) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{5}
}

func (m *WhereClauses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhereClauses.Unmarshal(m, b)
}
func (m *WhereClauses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhereClauses.Marshal(b, m, deterministic)
}
func (m *WhereClauses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhereClauses.Merge(m, src)
}
func (m *WhereClauses) XXX_Size() int {
	return xxx_messageInfo_WhereClauses.Size(m)
}
func (m *WhereClauses) XXX_DiscardUnknown() {
	xxx_messageInfo_WhereClauses.DiscardUnknown(m)
}

var xxx_messageInfo_WhereClauses proto.InternalMessageInfo

func (m *WhereClauses) GetClauses() []*WhereClause {
	if m != nil {
		return m.Clauses
	}
	return nil
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{6}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type JobResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quota                uint32   `protobuf:"varint,3,opt,name=quota,proto3" json:"quota,omitempty"`
	ExpiryDate           string   `protobuf:"bytes,4,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	JobPosterId          uint32   `protobuf:"varint,5,opt,name=job_poster_id,json=jobPosterId,proto3" json:"job_poster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResponse) Reset()         { *m = JobResponse{} }
func (m *JobResponse) String() string { return proto.CompactTextString(m) }
func (*JobResponse) ProtoMessage()    {}
func (*JobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{7}
}

func (m *JobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResponse.Unmarshal(m, b)
}
func (m *JobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResponse.Marshal(b, m, deterministic)
}
func (m *JobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResponse.Merge(m, src)
}
func (m *JobResponse) XXX_Size() int {
	return xxx_messageInfo_JobResponse.Size(m)
}
func (m *JobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobResponse proto.InternalMessageInfo

func (m *JobResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JobResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobResponse) GetQuota() uint32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *JobResponse) GetExpiryDate() string {
	if m != nil {
		return m.ExpiryDate
	}
	return ""
}

func (m *JobResponse) GetJobPosterId() uint32 {
	if m != nil {
		return m.JobPosterId
	}
	return 0
}

type ApplicationRequest struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobId                uint32   `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationRequest) Reset()         { *m = ApplicationRequest{} }
func (m *ApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*ApplicationRequest) ProtoMessage()    {}
func (*ApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{8}
}

func (m *ApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationRequest.Unmarshal(m, b)
}
func (m *ApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationRequest.Marshal(b, m, deterministic)
}
func (m *ApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationRequest.Merge(m, src)
}
func (m *ApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_ApplicationRequest.Size(m)
}
func (m *ApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationRequest proto.InternalMessageInfo

func (m *ApplicationRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ApplicationRequest) GetJobId() uint32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type UserProfile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Birthday             string   `protobuf:"bytes,3,opt,name=birthday,proto3" json:"birthday,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{9}
}

func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserProfile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfile) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

type UserDetail struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetail) Reset()         { *m = UserDetail{} }
func (m *UserDetail) String() string { return proto.CompactTextString(m) }
func (*UserDetail) ProtoMessage()    {}
func (*UserDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{10}
}

func (m *UserDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetail.Unmarshal(m, b)
}
func (m *UserDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetail.Marshal(b, m, deterministic)
}
func (m *UserDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetail.Merge(m, src)
}
func (m *UserDetail) XXX_Size() int {
	return xxx_messageInfo_UserDetail.Size(m)
}
func (m *UserDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetail.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetail proto.InternalMessageInfo

func (m *UserDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserDetail) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AllJobResponses struct {
	Message              string         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Responses            []*JobResponse `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AllJobResponses) Reset()         { *m = AllJobResponses{} }
func (m *AllJobResponses) String() string { return proto.CompactTextString(m) }
func (*AllJobResponses) ProtoMessage()    {}
func (*AllJobResponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{11}
}

func (m *AllJobResponses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllJobResponses.Unmarshal(m, b)
}
func (m *AllJobResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllJobResponses.Marshal(b, m, deterministic)
}
func (m *AllJobResponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllJobResponses.Merge(m, src)
}
func (m *AllJobResponses) XXX_Size() int {
	return xxx_messageInfo_AllJobResponses.Size(m)
}
func (m *AllJobResponses) XXX_DiscardUnknown() {
	xxx_messageInfo_AllJobResponses.DiscardUnknown(m)
}

var xxx_messageInfo_AllJobResponses proto.InternalMessageInfo

func (m *AllJobResponses) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AllJobResponses) GetResponses() []*JobResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type ApplicationResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               uint32   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	JobId                uint32   `protobuf:"varint,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AppliedAt            string   `protobuf:"bytes,5,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string   `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationResponse) Reset()         { *m = ApplicationResponse{} }
func (m *ApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*ApplicationResponse) ProtoMessage()    {}
func (*ApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{12}
}

func (m *ApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationResponse.Unmarshal(m, b)
}
func (m *ApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationResponse.Marshal(b, m, deterministic)
}
func (m *ApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationResponse.Merge(m, src)
}
func (m *ApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_ApplicationResponse.Size(m)
}
func (m *ApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationResponse proto.InternalMessageInfo

func (m *ApplicationResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ApplicationResponse) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ApplicationResponse) GetJobId() uint32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *ApplicationResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ApplicationResponse) GetAppliedAt() string {
	if m != nil {
		return m.AppliedAt
	}
	return ""
}

func (m *ApplicationResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ApplicationResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *ApplicationResponse) GetDeletedAt() string {
	if m != nil {
		return m.DeletedAt
	}
	return ""
}

type AllApplicationResponses struct {
	Message              string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Responses            []*ApplicationResponse `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AllApplicationResponses) Reset()         { *m = AllApplicationResponses{} }
func (m *AllApplicationResponses) String() string { return proto.CompactTextString(m) }
func (*AllApplicationResponses) ProtoMessage()    {}
func (*AllApplicationResponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_8283befe383e2552, []int{13}
}

func (m *AllApplicationResponses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllApplicationResponses.Unmarshal(m, b)
}
func (m *AllApplicationResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllApplicationResponses.Marshal(b, m, deterministic)
}
func (m *AllApplicationResponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllApplicationResponses.Merge(m, src)
}
func (m *AllApplicationResponses) XXX_Size() int {
	return xxx_messageInfo_AllApplicationResponses.Size(m)
}
func (m *AllApplicationResponses) XXX_DiscardUnknown() {
	xxx_messageInfo_AllApplicationResponses.DiscardUnknown(m)
}

var xxx_messageInfo_AllApplicationResponses proto.InternalMessageInfo

func (m *AllApplicationResponses) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AllApplicationResponses) GetResponses() []*ApplicationResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "job_application.UserRequest")
	proto.RegisterType((*UserLoginRequest)(nil), "job_application.UserLoginRequest")
	proto.RegisterType((*JobRequest)(nil), "job_application.JobRequest")
	proto.RegisterType((*IdRequest)(nil), "job_application.IdRequest")
	proto.RegisterType((*WhereClause)(nil), "job_application.WhereClause")
	proto.RegisterType((*WhereClauses)(nil), "job_application.WhereClauses")
	proto.RegisterType((*LoginResponse)(nil), "job_application.LoginResponse")
	proto.RegisterType((*JobResponse)(nil), "job_application.JobResponse")
	proto.RegisterType((*ApplicationRequest)(nil), "job_application.ApplicationRequest")
	proto.RegisterType((*UserProfile)(nil), "job_application.UserProfile")
	proto.RegisterType((*UserDetail)(nil), "job_application.UserDetail")
	proto.RegisterType((*AllJobResponses)(nil), "job_application.AllJobResponses")
	proto.RegisterType((*ApplicationResponse)(nil), "job_application.ApplicationResponse")
	proto.RegisterType((*AllApplicationResponses)(nil), "job_application.AllApplicationResponses")
}

func init() {
	proto.RegisterFile("proto/job_application.proto", fileDescriptor_8283befe383e2552)
}

var fileDescriptor_8283befe383e2552 = []byte{
	// 733 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xd1, 0x4e, 0xdb, 0x4a,
	0x10, 0x95, 0x1d, 0x48, 0xf0, 0x84, 0x5c, 0xd0, 0x5e, 0xee, 0x25, 0x0a, 0xd0, 0x52, 0xb7, 0x95,
	0x78, 0x02, 0x29, 0x95, 0x78, 0xe8, 0x5b, 0x20, 0xa2, 0x0a, 0xaa, 0x10, 0x32, 0x6a, 0x91, 0x2a,
	0xa1, 0xc8, 0xce, 0x2e, 0x61, 0xa9, 0xf1, 0x1a, 0xef, 0x1a, 0x1a, 0xf5, 0x17, 0xfa, 0x19, 0x7d,
	0x69, 0xff, 0xac, 0x7f, 0x51, 0xed, 0xae, 0x37, 0x71, 0x62, 0x27, 0xf0, 0x94, 0xcc, 0x9c, 0xf1,
	0xf8, 0xcc, 0x99, 0xb3, 0x6b, 0xd8, 0x8a, 0x13, 0x26, 0xd8, 0xc1, 0x2d, 0x0b, 0xfa, 0x7e, 0x1c,
	0x87, 0x74, 0xe0, 0x0b, 0xca, 0xa2, 0x7d, 0x95, 0x45, 0x6b, 0x33, 0x69, 0xf7, 0x1e, 0xea, 0x9f,
	0x38, 0x49, 0x3c, 0x72, 0x9f, 0x12, 0x2e, 0x10, 0x82, 0xa5, 0xc8, 0xbf, 0x23, 0x4d, 0x6b, 0xd7,
	0xda, 0x73, 0x3c, 0xf5, 0x1f, 0x6d, 0x83, 0x13, 0xd0, 0x44, 0xdc, 0x60, 0x5f, 0x90, 0xa6, 0xad,
	0x80, 0x49, 0x02, 0x6d, 0xc0, 0x32, 0xb9, 0xf3, 0x69, 0xd8, 0xac, 0x28, 0x44, 0x07, 0xa8, 0x05,
	0x2b, 0xb1, 0xcf, 0xf9, 0x23, 0x4b, 0x70, 0x73, 0x49, 0x01, 0xe3, 0xd8, 0xed, 0xc2, 0xba, 0x7c,
	0xe5, 0x47, 0x36, 0xa4, 0x91, 0x79, 0xef, 0xb8, 0x8b, 0x35, 0xaf, 0x8b, 0x3d, 0xd3, 0xe5, 0x3b,
	0xc0, 0x29, 0x0b, 0x16, 0xf1, 0xde, 0x80, 0xe5, 0xfb, 0x94, 0x09, 0x5f, 0x3d, 0xda, 0xf0, 0x74,
	0x80, 0x5e, 0x42, 0x9d, 0x7c, 0x8b, 0x69, 0x32, 0xea, 0xab, 0x79, 0x34, 0x6b, 0xd0, 0xa9, 0xae,
	0x1c, 0xc8, 0x85, 0x86, 0x14, 0x29, 0x66, 0x5c, 0x90, 0xa4, 0x4f, 0x35, 0xff, 0x86, 0x57, 0xbf,
	0x65, 0xc1, 0xb9, 0xca, 0xf5, 0xb0, 0xbb, 0x05, 0x4e, 0x0f, 0x9b, 0x77, 0xff, 0x03, 0x36, 0xc5,
	0xea, 0xcd, 0x0d, 0xcf, 0xa6, 0xd8, 0xbd, 0x84, 0xfa, 0xe5, 0x0d, 0x49, 0xc8, 0x71, 0xe8, 0xa7,
	0x5c, 0xd1, 0xb8, 0xa6, 0x24, 0xc4, 0x66, 0x34, 0x15, 0xc8, 0xec, 0x83, 0x1f, 0xa6, 0x46, 0x50,
	0x1d, 0x48, 0xa9, 0x07, 0x2c, 0xc2, 0x54, 0xae, 0x26, 0xa3, 0x36, 0x49, 0xb8, 0x27, 0xb0, 0x9a,
	0x6b, 0xcc, 0xd1, 0x21, 0xd4, 0x06, 0xfa, 0x6f, 0xd3, 0xda, 0xad, 0xec, 0xd5, 0xdb, 0xdb, 0xfb,
	0xb3, 0x5b, 0xcf, 0xd5, 0x7b, 0xa6, 0xd8, 0x7d, 0x0b, 0x8d, 0x4c, 0x7c, 0x1e, 0xb3, 0x48, 0x53,
	0x14, 0xec, 0x2b, 0x89, 0x0c, 0x45, 0x15, 0xb8, 0x3f, 0x2c, 0xa8, 0x2b, 0x89, 0xb3, 0xaa, 0x99,
	0x39, 0xc7, 0x9a, 0xdb, 0x65, 0x9a, 0x57, 0x16, 0x68, 0xbe, 0xf4, 0xb4, 0xe6, 0xcb, 0x45, 0xcd,
	0xbb, 0x80, 0x3a, 0x93, 0xc9, 0x8c, 0xf8, 0x9b, 0x50, 0x4b, 0xb9, 0x7e, 0x46, 0x33, 0xab, 0xca,
	0xb0, 0x87, 0xd1, 0x7f, 0x50, 0x95, 0x2d, 0x29, 0x36, 0xeb, 0xbf, 0x65, 0x41, 0x0f, 0xbb, 0x17,
	0xda, 0xef, 0xe7, 0x09, 0xbb, 0xa6, 0x21, 0x99, 0xe7, 0x1b, 0xed, 0x45, 0x7b, 0xc6, 0x8b, 0x99,
	0xe9, 0x47, 0xd9, 0x66, 0xc6, 0xb1, 0x7b, 0x08, 0x20, 0x9b, 0x76, 0x89, 0x90, 0x95, 0xcf, 0xee,
	0xe9, 0x0e, 0x61, 0xad, 0x13, 0x86, 0x39, 0x8d, 0x39, 0x6a, 0x42, 0xed, 0x8e, 0x70, 0xee, 0x0f,
	0xcd, 0xf3, 0x26, 0x44, 0xef, 0xc1, 0x49, 0x4c, 0x59, 0xd3, 0x9e, 0xb3, 0xef, 0x5c, 0x2f, 0x6f,
	0x52, 0xee, 0xfe, 0xb1, 0xe0, 0xdf, 0x29, 0xf1, 0xe6, 0xac, 0x34, 0xa7, 0xa6, 0x3d, 0x47, 0xcd,
	0x4a, 0x4e, 0x4d, 0xf4, 0x3f, 0x54, 0xb9, 0xf0, 0x45, 0xca, 0xb3, 0x9d, 0x66, 0x11, 0xda, 0x01,
	0x50, 0xac, 0x08, 0xee, 0xfb, 0x42, 0x2d, 0xd3, 0xf1, 0x9c, 0x2c, 0xd3, 0x11, 0x12, 0x1e, 0x24,
	0xc4, 0x17, 0x1a, 0xae, 0x66, 0x3e, 0xd7, 0x19, 0x0d, 0xa7, 0x31, 0x36, 0x70, 0x4d, 0xc3, 0x59,
	0x46, 0xc3, 0x98, 0x84, 0x24, 0x83, 0x57, 0x34, 0x9c, 0x65, 0x3a, 0xc2, 0x7d, 0x84, 0xcd, 0x4e,
	0x18, 0x96, 0x4c, 0xbb, 0x48, 0xdc, 0xa3, 0xa2, 0xb8, 0x6f, 0x0a, 0xe2, 0x96, 0xf4, 0xcc, 0x89,
	0xdc, 0xfe, 0x65, 0x69, 0x6f, 0x5d, 0x90, 0xe4, 0x81, 0x0e, 0x08, 0x3a, 0x85, 0x55, 0x8f, 0x0c,
	0xa9, 0xb4, 0xaf, 0x4c, 0xa3, 0xe2, 0xb6, 0x72, 0x37, 0x6f, 0xab, 0x1c, 0x35, 0x3e, 0x3d, 0x03,
	0x47, 0x1d, 0x59, 0xd5, 0xe8, 0x55, 0x69, 0x69, 0xfe, 0x3e, 0x6d, 0xbd, 0x28, 0x94, 0x4c, 0x9d,
	0xf8, 0xf6, 0x4f, 0x4b, 0x5d, 0x9f, 0x86, 0xea, 0x09, 0x38, 0xc7, 0x4a, 0xfe, 0x53, 0x16, 0xa0,
	0xad, 0x72, 0x57, 0xcd, 0xa3, 0x99, 0xbf, 0x22, 0xce, 0xa0, 0x7e, 0x42, 0x23, 0xac, 0x4d, 0xcd,
	0xd1, 0xce, 0xa2, 0xfb, 0x88, 0xb7, 0x76, 0x8b, 0x0a, 0x4f, 0x9f, 0x86, 0xf6, 0x6f, 0x7b, 0xea,
	0xd0, 0x1b, 0xba, 0x57, 0xb0, 0x2e, 0xb3, 0xa3, 0x1c, 0x84, 0x5e, 0x2f, 0x5e, 0x97, 0x66, 0xff,
	0xac, 0x9d, 0xa2, 0x2b, 0x40, 0x1f, 0x88, 0x98, 0x36, 0xd1, 0x93, 0xc3, 0xec, 0x95, 0x0d, 0x53,
	0xea, 0xc2, 0xcf, 0xba, 0xfd, 0x04, 0x3a, 0x1a, 0xf5, 0x30, 0x6a, 0x15, 0x9e, 0x1f, 0x7f, 0x61,
	0x9e, 0x47, 0xfb, 0xc8, 0xf9, 0x52, 0xdb, 0x3f, 0x50, 0x9f, 0xf9, 0xa0, 0xaa, 0x7e, 0xde, 0xfd,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x14, 0x42, 0x60, 0xd9, 0x0c, 0x08, 0x00, 0x00,
}
